import { http } from './http';

export const adminApi = {
  login: (payload) => http.post('/auth/login', payload),
  overview: () => http.get('/stats/overview'),
  products: (params) => http.get('/products', { params }),
  createProduct: (payload) => http.post('/products', payload),
  updateProduct: (id, payload) => http.put(`/products/${id}`, payload),
  deleteProduct: (id) => http.delete(`/products/${id}`),
  categories: (params) => http.get('/categories', { params }),
  createCategory: (payload) => http.post('/categories', payload),
  updateCategory: (id, payload) => http.put(`/categories/${id}`, payload),
  deleteCategory: (id) => http.delete(`/categories/${id}`),
  reviews: (params) => http.get('/reviews', { params }),
  replyReview: (id, payload) => http.put(`/reviews/${id}/reply`, payload),
  deleteReview: (id) => http.delete(`/reviews/${id}`),
  orders: (params) => http.get('/orders', { params }),
  shipOrder: (id, payload) => http.put(`/orders/${id}/ship`, payload),
  users: (params) => http.get('/users', { params }),
  toggleUser: (id) => http.put(`/users/${id}/status`),
  coupons: () => http.get('/coupons'),
  createCoupon: (payload) => http.post('/coupons', payload),
  banners: () => http.get('/banners'),
  createBanner: (payload) => http.post('/banners', payload),
  updateBanner: (id, payload) => http.put(`/banners/${id}`, payload),
  deleteBanner: (id) => http.delete(`/banners/${id}`),
  roles: () => http.get('/roles'),
  createRole: (payload) => http.post('/roles', payload),
  updateRole: (code, payload) => http.put(`/roles/${code}`, payload),
  deleteRole: (code) => http.delete(`/roles/${code}`),
  admins: () => http.get('/admins'),
  createAdmin: (payload) => http.post('/admins', payload),
  updateAdmin: (id, payload) => http.put(`/admins/${id}`, payload),
  deleteAdmin: (id) => http.delete(`/admins/${id}`)
};
