import { http } from './http';

export const mallApi = {
  sendCode: (phone) => http.post('/auth/send-code', { phone }),
  login: (payload) => http.post('/auth/login', payload),
  profile: () => http.get('/auth/info'),
  banners: () => http.get('/home/banners'),
  recommend: (limit = 8) => http.get('/home/recommend', { params: { limit } }),
  categories: () => http.get('/categories'),
  products: (params) => http.get('/products', { params }),
  product: (id) => http.get(`/products/${id}`),
  reviews: (productId) => http.get(`/products/${productId}/reviews`),
  createReview: (productId, payload) => http.post(`/products/${productId}/reviews`, payload),
  cart: () => http.get('/cart'),
  addCart: (payload) => http.post('/cart', payload),
  updateCart: (id, payload) => http.put(`/cart/${id}`, payload),
  removeCart: (id) => http.delete(`/cart/${id}`),
  addresses: () => http.get('/addresses'),
  createAddress: (payload) => http.post('/addresses', payload),
  updateAddress: (id, payload) => http.put(`/addresses/${id}`, payload),
  deleteAddress: (id) => http.delete(`/addresses/${id}`),
  createOrder: (payload) => http.post('/orders', payload),
  payOrder: (id) => http.post(`/orders/${id}/pay`),
  orders: () => http.get('/orders'),
  cancelOrder: (id) => http.put(`/orders/${id}/cancel`),
  favorites: () => http.get('/favorites'),
  favoriteStatus: (productId) => http.get(`/favorites/status/${productId}`),
  addFavorite: (productId) => http.post('/favorites', { productId }),
  removeFavorite: (id) => http.delete(`/favorites/${id}`),
  removeFavoriteByProduct: (productId) => http.delete(`/favorites/product/${productId}`),
  coupons: () => http.get('/coupons'),
  userCoupons: (params) => http.get('/user-coupons', { params }),
  receiveCoupon: (couponId) => http.post('/coupons/receive', { couponId })
};
